let shopItemsData = [
  //HATS
  {
    id: "merch_snapback_black_elr_gtr_white_orange",
    name: "Snapback - GTR Edition",
    price: 50,
    desc: "Black snapback with the ELR GTR edition logo",
    type: "hat",
    baseColor: "black",
    tags: ["gtr", "orange"],
    img: "../src/img/merch/hats/merch_snapback_black_elr_gtr_white_orange.png",
  },
  {
    id: "merch_snapback_black_elr_gtr_white_purple",
    name: "Snapback - GTR Edition",
    price: 50,
    desc: "Black snapback with the ELR GTR edition logo",
    type: "hat",
    baseColor: "black",
    tags: ["gtr", "purple"],
    img: "../src/img/merch/hats/merch_snapback_black_elr_gtr_white_purple.png",
  },
  {
    id: "merch_snapback_black_elr_gtr_white_red",
    name: "Snapback - GTR Edition",
    price: 50,
    desc: "Black snapback with the ELR GTR edition logo",
    type: "hat",
    baseColor: "black",
    tags: ["gtr", "red"],
    img: "../src/img/merch/hats/merch_snapback_black_elr_gtr_white_red.png",
  },
  {
    id: "merch_snapback_black_elr_gtr_white",
    name: "Snapback - GTR Edition",
    price: 50,
    desc: "Black snapback with the ELR GTR edition logo",
    type: "hat",
    baseColor: "black",
    tags: ["gtr", "white"],
    img: "../src/img/merch/hats/merch_snapback_black_elr_gtr_white.png",
  },
  {
    id: "merch_snapback_purple_elr_gtr_white_orange",
    name: "Snapback - GTR Edition",
    price: 50,
    desc: "Purple snapback with the GTR edition logo",
    type: "hat",
    baseColor: "purple",
    tags: ["gtr", "orange"],
    img: "../src/img/merch/hats/merch_snapback_purple_elr_gtr_white_orange.png",
  },
  {
    id: "merch_snapback_purple_elr_gtr_white_red",
    name: "Snapback - GTR Edition",
    price: 50,
    desc: "Purple snapback with the GTR edition logo",
    type: "hat",
    baseColor: "purple",
    tags: ["gtr", "red"],
    img: "../src/img/merch/hats/merch_snapback_purple_elr_gtr_white_red.png",
  },
  {
    id: "merch_snapback_purple_elr_gtr_white",
    name: "Snapback - GTR Edition",
    price: 50,
    desc: "Purple snapback with the GTR edition logo",
    type: "hat",
    baseColor: "purple",
    tags: ["gtr", "white"],
    img: "../src/img/merch/hats/merch_snapback_purple_elr_gtr_white.png",
  },
  {
    id: "merch_snapback_purple_elr_gtr_white",
    name: "Snapback - GTR Edition",
    price: 50,
    desc: "Purple snapback with the GTR edition logo",
    type: "hat",
    baseColor: "purple",
    tags: ["gtr", "white"],
    img: "../src/img/merch/hats/merch_snapback_purple_elr_gtr_white.png",
  },
  {
    id: "merch_snapback_white_elr_gtr_black_orange",
    name: "Snapback - GTR Edition",
    price: 50,
    desc: "White snapback with the GTR edition logo",
    type: "hat",
    baseColor: "white",
    tags: ["gtr", "orange"],
    img: "../src/img/merch/hats/merch_snapback_white_elr_gtr_black_orange.png",
  },
  {
    id: "merch_snapback_white_elr_gtr_black_purple",
    name: "Snapback - GTR Edition",
    price: 50,
    desc: "White snapback with the GTR edition logo",
    type: "hat",
    baseColor: "white",
    tags: ["gtr", "purple"],
    img: "../src/img/merch/hats/merch_snapback_white_elr_gtr_black_purple.png",
  },
  {
    id: "merch_snapback_white_elr_gtr_black",
    name: "Snapback - GTR Edition",
    price: 50,
    desc: "White snapback with the GTR edition logo",
    type: "hat",
    baseColor: "white",
    tags: ["gtr", "black"],
    img: "../src/img/merch/hats/merch_snapback_white_elr_gtr_black.png",
  },
  {
    id: "merch_snapback_white_elr_gtr_black_red",
    name: "Snapback - GTR Edition",
    price: 50,
    desc: "White snapback with the GTR edition logo",
    type: "hat",
    baseColor: "white",
    tags: ["gtr", "red"],
    img: "../src/img/merch/hats/merch_snapback_white_elr_gtr_black_red.png",
  },
  {
    id: "merch_snapback_black_elr_main_color",
    name: "Snapback - ELR",
    price: 50,
    desc: "Black snapback with the original ELR logo",
    type: "hat",
    baseColor: "black",
    tags: ["main", "color"],
    img: "../src/img/merch/hats/merch_snapback_black_elr_main_color.png",
  },
  {
    id: "merch_snapback_black_elr_main_white",
    name: "Snapback - ELR",
    price: 50,
    desc: "Black snapback with the original ELR logo",
    type: "hat",
    baseColor: "black",
    tags: ["main", "white"],
    img: "../src/img/merch/hats/merch_snapback_black_elr_main_white.png",
  },
  {
    id: "merch_snapback_purple_elr_main_color",
    name: "Snapback - ELR",
    price: 50,
    desc: "Purple snapback with the original ELR logo",
    type: "hat",
    baseColor: "purple",
    tags: ["main", "color"],
    img: "../src/img/merch/hats/merch_snapback_purple_elr_main_color.png",
  },
  {
    id: "merch_snapback_purple_elr_main_white",
    name: "Snapback - ELR",
    price: 50,
    desc: "Purple snapback with the original ELR logo",
    type: "hat",
    baseColor: "purple",
    tags: ["main", "white"],
    img: "../src/img/merch/hats/merch_snapback_purple_elr_main_white.png",
  },
  {
    id: "merch_snapback_white_elr_main_black",
    name: "Snapback - ELR",
    price: 50,
    desc: "White snapback with the original ELR logo",
    type: "hat",
    baseColor: "white",
    tags: ["main", "black"],
    img: "../src/img/merch/hats/merch_snapback_white_elr_main_black.png",
  },
  {
    id: "merch_snapback_white_elr_main_purple",
    name: "Snapback - ELR",
    price: 50,
    desc: "White snapback with the original ELR logo",
    type: "hat",
    baseColor: "white",
    tags: ["main", "purple"],
    img: "../src/img/merch/hats/merch_snapback_white_elr_main_purple.png",
  },
  {
    id: "merch_snapback_black_elr_monogram_white",
    name: "Snapback - Monogram Edition",
    price: 50,
    desc: "Black snapback with the Monogram edition logo",
    type: "hat",
    baseColor: "black",
    tags: ["monogram", "white"],
    img: "../src/img/merch/hats/merch_snapback_black_elr_monogram_white.png",
  },
  {
    id: "merch_snapback_purple_elr_monogram_white_stroke",
    name: "Snapback - Monogram Edition",
    price: 50,
    desc: "Black snapback with the Monogram edition logo",
    type: "hat",
    baseColor: "purple",
    tags: ["monogram", "white"],
    img: "../src/img/merch/hats/merch_snapback_purple_elr_monogram_white_stroke.png",
  },
  {
    id: "merch_snapback_purple_elr_monogram_white",
    name: "Snapback - Monogram Edition",
    price: 50,
    desc: "Black snapback with the Monogram edition logo",
    type: "hat",
    baseColor: "purple",
    tags: ["monogram", "white"],
    img: "../src/img/merch/hats/merch_snapback_purple_elr_monogram_white.png",
  },
  {
    id: "merch_snapback_white_elr_monogram_black",
    name: "Snapback - Monogram Edition",
    price: 50,
    desc: "Black snapback with the Monogram edition logo",
    type: "hat",
    baseColor: "white",
    tags: ["monogram", "black"],
    img: "../src/img/merch/hats/merch_snapback_white_elr_monogram_black.png",
  },

  // HOODIES

  {
    id: "merch_hoodie_black_elr_gtr_white_orange",
    name: "Hoodie - GTR Edition",
    price: 50,
    desc: "Black hoodie with the Monogram edition logo",
    type: "hoodie",
    baseColor: "black",
    tags: ["gtr", "orange"],
    img: "../src/img/merch/hoodies/merch_hoodie_black_elr_gtr_white_orange.png",
  },
  {
    id: "merch_hoodie_black_elr_gtr_white_purple",
    name: "Hoodie - GTR Edition",
    price: 50,
    desc: "Black hoodie with the Monogram edition logo",
    type: "hoodie",
    baseColor: "black",
    tags: ["gtr", "purple"],
    img: "../src/img/merch/hoodies/merch_hoodie_black_elr_gtr_white_purple.png",
  },
  {
    id: "merch_hoodie_black_elr_gtr_white_red",
    name: "Hoodie - GTR Edition",
    price: 50,
    desc: "Black hoodie with the Monogram edition logo",
    type: "hoodie",
    baseColor: "black",
    tags: ["gtr", "red"],
    img: "../src/img/merch/hoodies/merch_hoodie_black_elr_gtr_white_red.png",
  },
  {
    id: "merch_hoodie_black_elr_gtr_white",
    name: "Hoodie - GTR Edition",
    price: 50,
    desc: "Black hoodie with the Monogram edition logo",
    type: "hoodie",
    baseColor: "black",
    tags: ["gtr", "white"],
    img: "../src/img/merch/hoodies/merch_hoodie_black_elr_gtr_white.png",
  },
  {
    id: "merch_hoodie_purple_elr_gtr_white_orange",
    name: "Snapback - Monogram EditionHoodie - GTR Edition",
    price: 50,
    desc: "Purple hoodie with the Monogram edition logo",
    type: "hoodie",
    baseColor: "purple",
    tags: ["gtr", "orange"],
    img: "../src/img/merch/hoodies/merch_hoodie_purple_elr_gtr_white_orange.png",
  },
  {
    id: "merch_hoodie_purple_elr_gtr_white",
    name: "Hoodie - GTR Edition",
    price: 50,
    desc: "Purple hoodie with the Monogram edition logo",
    type: "hoodie",
    baseColor: "purple",
    tags: ["gtr", "white"],
    img: "../src/img/merch/hoodies/merch_hoodie_purple_elr_gtr_white.png",
  },
  {
    id: "merch_hoodie_white_elr_gtr_black_orange",
    name: "Hoodie - GTR Edition",
    price: 50,
    desc: "White hoodie with the Monogram edition logo",
    type: "hoodie",
    baseColor: "white",
    tags: ["gtr", "oranange"],
    img: "../src/img/merch/hoodies/merch_hoodie_white_elr_gtr_black_orange.png",
  },
  {
    id: "merch_hoodie_white_elr_gtr_black_purple",
    name: "Hoodie - GTR Edition",
    price: 50,
    desc: "White hoodie with the Monogram edition logo",
    type: "hoodie",
    baseColor: "white",
    tags: ["gtr", "purple"],
    img: "../src/img/merch/hoodies/merch_hoodie_white_elr_gtr_black_purple.png",
  },
  {
    id: "merch_hoodie_white_elr_gtr_black",
    name: "Hoodie - GTR Edition",
    price: 50,
    desc: "White hoodie with the Monogram edition logo",
    type: "hoodie",
    baseColor: "white",
    tags: ["gtr", "black"],
    img: "../src/img/merch/hoodies/merch_hoodie_white_elr_gtr_black.png",
  },
  {
    id: "merch_hoodie_black_elr_main_color",
    name: "Hoodie - ELR",
    price: 50,
    desc: "Black hoodie with the ELR logo",
    type: "hoodie",
    baseColor: "black",
    tags: ["main", "color"],
    img: "../src/img/merch/hoodies/merch_hoodie_black_elr_main_color.png",
  },
  {
    id: "merch_hoodie_black_elr_main_white",
    name: "Hoodie - ELR",
    price: 50,
    desc: "Black hoodie with the ELR logo",
    type: "hoodie",
    baseColor: "black",
    tags: ["main", "white"],
    img: "../src/img/merch/hoodies/merch_hoodie_black_elr_main_white.png",
  },
  {
    id: "merch_hoodie_purple_elr_main_black_white",
    name: "Hoodie - ELR",
    price: 50,
    desc: "Purple hoodie with the ELR logo",
    type: "hoodie",
    baseColor: "purple",
    tags: ["main", "white"],
    img: "../src/img/merch/hoodies/merch_hoodie_purple_elr_main_black_white.png",
  },
  {
    id: "merch_hoodie_purple_elr_main_color",
    name: "Hoodie - ELR",
    price: 50,
    desc: "Purple hoodie with the ELR logo",
    type: "hoodie",
    baseColor: "purple",
    tags: ["main", "color"],
    img: "../src/img/merch/hoodies/merch_hoodie_purple_elr_main_color.png",
  },
  {
    id: "merch_hoodie_purple_elr_main_white",
    name: "Hoodie - ELR",
    price: 50,
    desc: "Purple hoodie with the ELR logo",
    type: "hoodie",
    baseColor: "purple",
    tags: ["main", "white"],
    img: "../src/img/merch/hoodies/merch_hoodie_purple_elr_main_white.png",
  },
  {
    id: "merch_hoodie_white_elr_main_black_white",
    name: "Hoodie - ELR",
    price: 50,
    desc: "White hoodie with the ELR logo",
    type: "hoodie",
    baseColor: "white",
    tags: ["main", "white"],
    img: "../src/img/merch/hoodies/merch_hoodie_white_elr_main_black_white.png",
  },
  {
    id: "merch_hoodie_white_elr_main_black",
    name: "Hoodie - ELR",
    price: 50,
    desc: "White hoodie with the ELR logo",
    type: "hoodie",
    baseColor: "white",
    tags: ["main", "black"],
    img: "../src/img/merch/hoodies/merch_hoodie_white_elr_main_black.png",
  },
  {
    id: "merch_hoodie_white_elr_main_color",
    name: "Hoodie - ELR",
    price: 50,
    desc: "White hoodie with the ELR logo",
    type: "hoodie",
    baseColor: "white",
    tags: ["main", "color"],
    img: "../src/img/merch/hoodies/merch_hoodie_white_elr_main_color.png",
  },
  {
    id: "merch_hoodie_black_elr_monogram_white",
    name: "Hoodie - Monogram Edition",
    price: 50,
    desc: "Black hoodie with the Monogram logo",
    type: "hoodie",
    baseColor: "black",
    tags: ["monogram", "white"],
    img: "../src/img/merch/hoodies/merch_hoodie_black_elr_monogram_white.png",
  },
  {
    id: "merch_hoodie_purple_elr_monogram_white_stroke",
    name: "Hoodie - Monogram Edition",
    price: 50,
    desc: "Purple hoodie with the Monogram logo",
    type: "hoodie",
    baseColor: "purple",
    tags: ["monogram", "white"],
    img: "../src/img/merch/hoodies/merch_hoodie_purple_elr_monogram_white_stroke.png",
  },
  {
    id: "merch_hoodie_purple_elr_monogram_white",
    name: "Hoodie - Monogram Edition",
    price: 50,
    desc: "Purple hoodie with the Monogram logo",
    type: "hoodie",
    baseColor: "purple",
    tags: ["monogram", "white"],
    img: "../src/img/merch/hoodies/merch_hoodie_purple_elr_monogram_white.png",
  },
  {
    id: "merch_hoodie_white_elr_monogram_black",
    name: "Hoodie - Monogram Edition",
    price: 50,
    desc: "White hoodie with the Monogram logo",
    type: "hoodie",
    baseColor: "white",
    tags: ["monogram", "black"],
    img: "../src/img/merch/hoodies/merch_hoodie_white_elr_monogram_black.png",
  },

  // shirts

  {
    id: "merch_tshirt_black_elr_gtr_orange",
    name: "Shirt - GTR Edition",
    price: 50,
    desc: "Black shirt with the ELR GTR logo",
    type: "shirt",
    baseColor: "black",
    tags: ["gtr", "orange"],
    img: "../src/img/merch/shirts/merch_tshirt_black_elr_gtr_orange.png",
  },
  {
    id: "merch_tshirt_black_elr_gtr_red",
    name: "Shirt - GTR Edition",
    price: 50,
    desc: "Black shirt with the ELR GTR logo",
    type: "shirt",
    baseColor: "black",
    tags: ["gtr", "red"],
    img: "../src/img/merch/shirts/merch_tshirt_black_elr_gtr_red.png",
  },
  {
    id: "merch_tshirt_black_elr_gtr_white_purple",
    name: "Shirt - GTR Edition",
    price: 50,
    desc: "Black shirt with the ELR GTR logo",
    type: "shirt",
    baseColor: "black",
    tags: ["gtr", "purple"],
    img: "../src/img/merch/shirts/merch_tshirt_black_elr_gtr_white_purple.png",
  },
  {
    id: "merch_tshirt_black_elr_gtr_white_stroke",
    name: "Shirt - GTR Edition",
    price: 50,
    desc: "Black shirt with the ELR GTR logo",
    type: "shirt",
    baseColor: "black",
    tags: ["gtr", "white"],
    img: "../src/img/merch/shirts/merch_tshirt_black_elr_gtr_white_stroke.png",
  },
  {
    id: "merch_tshirt_black_elr_main_color",
    name: "Shirt - ELR",
    price: 50,
    desc: "Black shirt with the ELR logo",
    type: "shirt",
    baseColor: "black",
    tags: ["main", "color"],
    img: "../src/img/merch/shirts/merch_tshirt_black_elr_main_color.png",
  },
  {
    id: "merch_tshirt_black_elr_main_white",
    name: "Shirt - ELR",
    price: 50,
    desc: "Black shirt with the ELR logo",
    type: "shirt",
    baseColor: "black",
    tags: ["main", "white"],
    img: "../src/img/merch/shirts/merch_tshirt_black_elr_main_white.png",
  },
  {
    id: "merch_tshirt_black_elr_monogram_color",
    name: "Shirt - Monogram Edition",
    price: 50,
    desc: "Black shirt with the Monogram logo",
    type: "shirt",
    baseColor: "black",
    tags: ["monogram", "color"],
    img: "../src/img/merch/shirts/merch_tshirt_black_elr_monogram_color.png",
  },
  {
    id: "merch_tshirt_black_elr_monogram_white",
    name: "Shirt - Monogram Edition",
    price: 50,
    desc: "Black shirt with the Monogram logo",
    type: "shirt",
    baseColor: "black",
    tags: ["monogram", "white"],
    img: "../src/img/merch/shirts/merch_tshirt_black_elr_monogram_white.png",
  },
  {
    id: "merch_tshirt_purple_elr_gtr_black",
    name: "Shirt - GTR Edition",
    price: 50,
    desc: "Purple shirt with the ELR GTR logo",
    type: "shirt",
    baseColor: "purple",
    tags: ["gtr", "black"],
    img: "../src/img/merch/shirts/merch_tshirt_purple_elr_gtr_black.png",
  },
  {
    id: "merch_tshirt_purple_elr_gtr_white_orange",
    name: "Shirt - GTR Edition",
    price: 50,
    desc: "Purple shirt with the ELR GTR logo",
    type: "shirt",
    baseColor: "purple",
    tags: ["gtr", "orange"],
    img: "../src/img/merch/shirts/merch_tshirt_purple_elr_gtr_white_orange.png",
  },
  {
    id: "merch_tshirt_purple_elr_gtr_white_red",
    name: "Shirt - GTR Edition",
    price: 50,
    desc: "Purple shirt with the ELR GTR logo",
    type: "shirt",
    baseColor: "purple",
    tags: ["gtr", "red"],
    img: "../src/img/merch/shirts/merch_tshirt_purple_elr_gtr_white_red.png",
  },
  {
    id: "merch_tshirt_purple_elr_gtr_white",
    name: "Shirt - GTR Edition",
    price: 50,
    desc: "Purple shirt with the ELR GTR logo",
    type: "shirt",
    baseColor: "purple",
    tags: ["gtr", "white"],
    img: "../src/img/merch/shirts/merch_tshirt_purple_elr_gtr_white.png",
  },
  {
    id: "merch_tshirt_purple_elr_main_black",
    name: "Shirt - ELR",
    price: 50,
    desc: "Purple shirt with the ELR logo",
    type: "shirt",
    baseColor: "purple",
    tags: ["main", "black"],
    img: "../src/img/merch/shirts/merch_tshirt_purple_elr_main_black.png",
  },
  {
    id: "merch_tshirt_purple_elr_main_white",
    name: "Shirt - ELR",
    price: 50,
    desc: "Purple shirt with the ELR logo",
    type: "shirt",
    baseColor: "purple",
    tags: ["main", "white"],
    img: "../src/img/merch/shirts/merch_tshirt_purple_elr_main_white.png",
  },
  {
    id: "merch_tshirt_purple_elr_monogram_black",
    name: "Shirt - Monogram Edition",
    price: 50,
    desc: "Purple shirt with the Monogram logo",
    type: "shirt",
    baseColor: "purple",
    tags: ["monogram", "black"],
    img: "../src/img/merch/shirts/merch_tshirt_purple_elr_monogram_black.png",
  },
  {
    id: "merch_tshirt_purple_elr_monogram_white",
    name: "Shirt - Monogram Edition",
    price: 50,
    desc: "Purple shirt with the Monogram logo",
    type: "shirt",
    baseColor: "purple",
    tags: ["monogram", "white"],
    img: "../src/img/merch/shirts/merch_tshirt_purple_elr_monogram_white.png",
  },
  {
    id: "merch_tshirt_white_elr_gtr_black_orange",
    name: "Shirt - GTR Edition",
    price: 50,
    desc: "White shirt with the ELR GTR logo",
    type: "shirt",
    baseColor: "white",
    tags: ["gtr", "orange"],
    img: "../src/img/merch/shirts/merch_tshirt_white_elr_gtr_black_orange.png",
  },
  {
    id: "merch_tshirt_white_elr_gtr_black_purple",
    name: "Shirt - GTR Edition",
    price: 50,
    desc: "White shirt with the ELR GTR logo",
    type: "shirt",
    baseColor: "white",
    tags: ["gtr", "purple"],
    img: "../src/img/merch/shirts/merch_tshirt_white_elr_gtr_black_purple.png",
  },
  {
    id: "merch_tshirt_white_elr_gtr_black_red",
    name: "Shirt - GTR Edition",
    price: 50,
    desc: "White shirt with the ELR GTR logo",
    type: "shirt",
    baseColor: "white",
    tags: ["gtr", "red"],
    img: "../src/img/merch/shirts/merch_tshirt_white_elr_gtr_black_red.png",
  },
  {
    id: "merch_tshirt_white_elr_gtr_black",
    name: "Shirt - GTR Edition",
    price: 50,
    desc: "Black shirt with the ELR GTR logo",
    type: "shirt",
    baseColor: "white",
    tags: ["gtr", "black"],
    img: "../src/img/merch/shirts/merch_tshirt_white_elr_gtr_black.png",
  },
  {
    id: "merch_tshirt_white_elr_main_black",
    name: "Shirt - ELR",
    price: 50,
    desc: "White shirt with the ELR logo",
    type: "shirt",
    baseColor: "white",
    tags: ["main", "black"],
    img: "../src/img/merch/shirts/merch_tshirt_white_elr_main_black.png",
  },
  {
    id: "merch_tshirt_white_elr_monogram_gradient",
    name: "Shirt - Monogram Edition",
    price: 50,
    desc: "White shirt with the ELR Monogram logo",
    type: "shirt",
    baseColor: "white",
    tags: ["monogram", "color"],
    img: "../src/img/merch/shirts/merch_tshirt_white_elr_monogram_gradient.png",
  },
  {
    id: "merch_tshirt_white_elr_monogram_orange",
    name: "Shirt - Monogram Edition",
    price: 50,
    desc: "White shirt with the ELR Monogram logo",
    type: "shirt",
    baseColor: "white",
    tags: ["monogram", "orange"],
    img: "../src/img/merch/shirts/merch_tshirt_white_elr_monogram_orange.png",
  },
  {
    id: "merch_tshirt_white_elr_monogram_purple",
    name: "Shirt - Monogram Edition",
    price: 50,
    desc: "White shirt with the ELR Monogram logo",
    type: "shirt",
    baseColor: "white",
    tags: ["monogram", "purple"],
    img: "../src/img/merch/shirts/merch_tshirt_white_elr_monogram_purple.png",
  },

  //sticker

  {
    id: "merch_sticker_black_elr_main_color",
    name: "Sticker",
    price: 50,
    desc: "Black shirt with the ELR GTR logo",
    type: "sticker",
    baseColor: "black",
    tags: ["main", "color"],
    img: "../src/img/merch/stickers/merch_sticker_black_elr_main_color.png",
  },
  {
    id: "merch_sticker_black_elr_main_white",
    name: "Sticker",
    price: 50,
    desc: "Black shirt with the ELR GTR logo",
    type: "sticker",
    baseColor: "black",
    tags: ["main", "white"],
    img: "../src/img/merch/stickers/merch_sticker_black_elr_main_white.png",
  },
  {
    id: "merch_sticker_black_elr_monogram_color",
    name: "Sticker",
    price: 50,
    desc: "Black shirt with the ELR GTR logo",
    type: "sticker",
    baseColor: "black",
    tags: ["monogram", "color"],
    img: "../src/img/merch/stickers/merch_sticker_black_elr_monogram_color.png",
  },
  {
    id: "merch_sticker_black_elr_monogram_orange_holo",
    name: "Sticker",
    price: 50,
    desc: "Black shirt with the ELR GTR logo",
    type: "sticker",
    baseColor: "black",
    tags: ["monogram", "orange"],
    img: "../src/img/merch/stickers/merch_sticker_black_elr_monogram_orange_holo.png",
  },
  {
    id: "merch_sticker_black_elr_monogram_orange",
    name: "Sticker",
    price: 50,
    desc: "Black shirt with the ELR GTR logo",
    type: "sticker",
    baseColor: "black",
    tags: ["monogram", "orange"],
    img: "../src/img/merch/stickers/merch_sticker_black_elr_monogram_orange.png",
  },
  {
    id: "merch_sticker_black_elr_monogram_purple_holo",
    name: "Sticker",
    price: 50,
    desc: "Black shirt with the ELR GTR logo",
    type: "sticker",
    baseColor: "black",
    tags: ["monogram", "purple"],
    img: "../src/img/merch/stickers/merch_sticker_black_elr_monogram_purple_holo.png",
  },
  {
    id: "merch_sticker_black_elr_monogram_purple",
    name: "Sticker",
    price: 50,
    desc: "Black shirt with the ELR GTR logo",
    type: "sticker",
    baseColor: "black",
    tags: ["monogram", "purple"],
    img: "../src/img/merch/stickers/merch_sticker_black_elr_monogram_purple.png",
  },
  {
    id: "merch_sticker_black_elr_monogram_white",
    name: "Sticker",
    price: 50,
    desc: "Black shirt with the ELR GTR logo",
    type: "sticker",
    baseColor: "black",
    tags: ["monogram", "white"],
    img: "../src/img/merch/stickers/merch_sticker_black_elr_monogram_white.png",
  },
  {
    id: "merch_sticker_white_elr_gtr_black_orange_holo",
    name: "Sticker",
    price: 50,
    desc: "Black shirt with the ELR GTR logo",
    type: "sticker",
    baseColor: "white",
    tags: ["gtr", "orange"],
    img: "../src/img/merch/stickers/merch_sticker_white_elr_gtr_black_orange_holo.png",
  },
  {
    id: "merch_sticker_white_elr_gtr_black_orange",
    name: "Sticker",
    price: 50,
    desc: "Black shirt with the ELR GTR logo",
    type: "sticker",
    baseColor: "white",
    tags: ["gtr", "orange"],
    img: "../src/img/merch/stickers/merch_sticker_white_elr_gtr_black_orange.png",
  },
  {
    id: "merch_sticker_white_elr_gtr_black_purple_holo",
    name: "Sticker",
    price: 50,
    desc: "Black shirt with the ELR GTR logo",
    type: "sticker",
    baseColor: "white",
    tags: ["gtr", "purple"],
    img: "../src/img/merch/stickers/merch_sticker_white_elr_gtr_black_purple_holo.png",
  },
  {
    id: "merch_sticker_white_elr_gtr_black_purple",
    name: "Sticker",
    price: 50,
    desc: "Black shirt with the ELR GTR logo",
    type: "sticker",
    baseColor: "white",
    tags: ["gtr", "purple"],
    img: "../src/img/merch/stickers/merch_sticker_white_elr_gtr_black_purple.png",
  },
  {
    id: "merch_sticker_white_elr_gtr_black_red",
    name: "Sticker",
    price: 50,
    desc: "Black shirt with the ELR GTR logo",
    type: "sticker",
    baseColor: "white",
    tags: ["gtr", "red"],
    img: "../src/img/merch/stickers/merch_sticker_white_elr_gtr_black_red.png",
  },
  {
    id: "merch_sticker_white_elr_gtr_black",
    name: "Sticker",
    price: 50,
    desc: "Black shirt with the ELR GTR logo",
    type: "sticker",
    baseColor: "white",
    tags: ["gtr", "black"],
    img: "../src/img/merch/stickers/merch_sticker_white_elr_gtr_black.png",
  },
  {
    id: "merch_sticker_white_elr_gtr_holo",
    name: "Sticker",
    price: 50,
    desc: "Black shirt with the ELR GTR logo",
    type: "sticker",
    baseColor: "white",
    tags: ["gtr", "color"],
    img: "../src/img/merch/stickers/merch_sticker_white_elr_gtr_holo.png",
  },
  {
    id: "merch_sticker_white_elr_main_black",
    name: "Sticker",
    price: 50,
    desc: "Black shirt with the ELR GTR logo",
    type: "sticker",
    baseColor: "white",
    tags: ["main", "black"],
    img: "../src/img/merch/stickers/merch_sticker_white_elr_main_black.png",
  },
  {
    id: "merch_sticker_white_elr_main_color_holo",
    name: "Sticker",
    price: 50,
    desc: "Black shirt with the ELR GTR logo",
    type: "sticker",
    baseColor: "white",
    tags: ["main", "color"],
    img: "../src/img/merch/stickers/merch_sticker_white_elr_main_color_holo.png",
  },
  {
    id: "merch_sticker_white_elr_monogram_black",
    name: "Sticker",
    price: 50,
    desc: "Black shirt with the ELR GTR logo",
    type: "sticker",
    baseColor: "white",
    tags: ["monogram", "black"],
    img: "../src/img/merch/stickers/merch_sticker_white_elr_monogram_black.png",
  },
  {
    id: "merch_sticker_white_elr_monogram_color_holo",
    name: "Sticker",
    price: 50,
    desc: "Black shirt with the ELR GTR logo",
    type: "sticker",
    baseColor: "white",
    tags: ["monogram", "color"],
    img: "../src/img/merch/stickers/merch_sticker_white_elr_monogram_color_holo.png",
  },
  {
    id: "merch_sticker_white_elr_monogram_color",
    name: "Sticker",
    price: 50,
    desc: "Black shirt with the ELR GTR logo",
    type: "sticker",
    baseColor: "white",
    tags: ["monogram", "color"],
    img: "../src/img/merch/stickers/merch_sticker_white_elr_monogram_color.png",
  },
  {
    id: "merch_sticker_white_elr_monogram_orange_holo",
    name: "Sticker",
    price: 50,
    desc: "Black shirt with the ELR GTR logo",
    type: "sticker",
    baseColor: "white",
    tags: ["monogram", "orange"],
    img: "../src/img/merch/stickers/merch_sticker_white_elr_monogram_orange_holo.png",
  },
  {
    id: "merch_sticker_white_elr_monogram_orange",
    name: "Sticker",
    price: 50,
    desc: "Black shirt with the ELR GTR logo",
    type: "sticker",
    baseColor: "white",
    tags: ["monogram", "orange"],
    img: "../src/img/merch/stickers/merch_sticker_white_elr_monogram_orange.png",
  },
  {
    id: "merch_sticker_white_elr_monogram_purple_holo",
    name: "Sticker",
    price: 50,
    desc: "Black shirt with the ELR GTR logo",
    type: "sticker",
    baseColor: "white",
    tags: ["monogram", "purple"],
    img: "../src/img/merch/stickers/merch_sticker_white_elr_monogram_purple_holo.png",
  },
  {
    id: "merch_sticker_white_elr_monogram_purple",
    name: "Sticker",
    price: 50,
    desc: "Black shirt with the ELR GTR logo",
    type: "sticker",
    baseColor: "white",
    tags: ["monogram", "purple"],
    img: "../src/img/merch/stickers/merch_sticker_white_elr_monogram_purple.png",
  },

  //scent trees

  {
    id: "merch_scenttree_black_elr_gtr_color",
    name: "Scent Tree - GTR Edition",
    price: 50,
    desc: "GTR edition scent tree",
    type: "tree",
    baseColor: "black",
    tags: ["gtr", "color"],
    img: "../src/img/merch/trees/merch_scenttree_black_elr_gtr_color.png",
  },
  {
    id: "merch_scenttree_black_elr_gtr_white_purple",
    name: "Scent Tree - GTR Edition",
    price: 50,
    desc: "GTR edition scent tree",
    type: "tree",
    baseColor: "black",
    tags: ["gtr", "purple"],
    img: "../src/img/merch/trees/merch_scenttree_black_elr_gtr_white_purple.png",
  },
  {
    id: "merch_scenttree_black_elr_gtr_white_red",
    name: "Scent Tree - GTR Edition",
    price: 50,
    desc: "GTR edition scent tree",
    type: "tree",
    baseColor: "black",
    tags: ["gtr", "red"],
    img: "../src/img/merch/trees/merch_scenttree_black_elr_gtr_white_red.png",
  },
  {
    id: "merch_scenttree_black_elr_gtr_white",
    name: "Scent Tree - GTR Edition",
    price: 50,
    desc: "GTR edition scent tree",
    type: "tree",
    baseColor: "black",
    tags: ["gtr", "white"],
    img: "../src/img/merch/trees/merch_scenttree_black_elr_gtr_white.png",
  },
  {
    id: "merch_scenttree_black_elr_main_color",
    name: "Scent Tree - GTR Edition",
    price: 50,
    desc: "GTR edition scent tree",
    type: "tree",
    baseColor: "black",
    tags: ["main", "color"],
    img: "../src/img/merch/trees/merch_scenttree_black_elr_main_color.png",
  },
  {
    id: "merch_scenttree_black_elr_main_white",
    name: "Scent Tree - GTR Edition",
    price: 50,
    desc: "GTR edition scent tree",
    type: "tree",
    baseColor: "black",
    tags: ["main", "white"],
    img: "../src/img/merch/trees/merch_scenttree_black_elr_main_white.png",
  },
  {
    id: "merch_scenttree_black_elr_monogram_color",
    name: "Scent Tree - GTR Edition",
    price: 50,
    desc: "GTR edition scent tree",
    type: "tree",
    baseColor: "black",
    tags: ["monogram", "color"],
    img: "../src/img/merch/trees/merch_scenttree_black_elr_monogram_color.png",
  },
  {
    id: "merch_scenttree_black_elr_monogram_white",
    name: "Scent Tree - GTR Edition",
    price: 50,
    desc: "GTR edition scent tree",
    type: "tree",
    baseColor: "black",
    tags: ["monogram", "white"],
    img: "../src/img/merch/trees/merch_scenttree_black_elr_monogram_white.png",
  },
  {
    id: "merch_scenttree_orange_elr_gtr_black",
    name: "Scent Tree - GTR Edition",
    price: 50,
    desc: "GTR edition scent tree",
    type: "tree",
    baseColor: "orange",
    tags: ["gtr", "black"],
    img: "../src/img/merch/trees/merch_scenttree_orange_elr_gtr_black.png",
  },
  {
    id: "merch_scenttree_orange_elr_main_white",
    name: "Scent Tree - GTR Edition",
    price: 50,
    desc: "GTR edition scent tree",
    type: "tree",
    baseColor: "orange",
    tags: ["main", "white"],
    img: "../src/img/merch/trees/merch_scenttree_orange_elr_main_white.png",
  },
  {
    id: "merch_scenttree_orange_elr_monogram_white",
    name: "Scent Tree - GTR Edition",
    price: 50,
    desc: "GTR edition scent tree",
    type: "tree",
    baseColor: "orange",
    tags: ["monogram", "white"],
    img: "../src/img/merch/trees/merch_scenttree_orange_elr_monogram_white.png",
  },
  {
    id: "merch_scenttree_purple_elr_gtr_black_purple",
    name: "Scent Tree - GTR Edition",
    price: 50,
    desc: "GTR edition scent tree",
    type: "tree",
    baseColor: "purple",
    tags: ["gtr", "purple"],
    img: "../src/img/merch/trees/merch_scenttree_purple_elr_gtr_black_purple.png",
  },
  {
    id: "merch_scenttree_purple_elr_gtr_black_red",
    name: "Scent Tree - GTR Edition",
    price: 50,
    desc: "GTR edition scent tree",
    type: "tree",
    baseColor: "purple",
    tags: ["gtr", "red"],
    img: "../src/img/merch/trees/merch_scenttree_purple_elr_gtr_black_red.png",
  },
  {
    id: "merch_scenttree_purple_elr_gtr_black",
    name: "Scent Tree - GTR Edition",
    price: 50,
    desc: "GTR edition scent tree",
    type: "tree",
    baseColor: "purple",
    tags: ["main", "black"],
    img: "../src/img/merch/trees/merch_scenttree_purple_elr_gtr_black.png",
  },
  {
    id: "merch_scenttree_purple_elr_gtr_white_orange",
    name: "Scent Tree - GTR Edition",
    price: 50,
    desc: "GTR edition scent tree",
    type: "tree",
    baseColor: "purple",
    tags: ["gtr", "orange"],
    img: "../src/img/merch/trees/merch_scenttree_purple_elr_gtr_white_orange.png",
  },
  {
    id: "merch_scenttree_purple_elr_gtr_white_purple",
    name: "Scent Tree - GTR Edition",
    price: 50,
    desc: "GTR edition scent tree",
    type: "tree",
    baseColor: "purple",
    tags: ["gtr", "purple"],
    img: "../src/img/merch/trees/merch_scenttree_purple_elr_gtr_white_purple.png",
  },
  {
    id: "merch_scenttree_purple_elr_gtr_white",
    name: "Scent Tree - GTR Edition",
    price: 50,
    desc: "GTR edition scent tree",
    type: "tree",
    baseColor: "purple",
    tags: ["gtr", "white"],
    img: "../src/img/merch/trees/merch_scenttree_purple_elr_gtr_white.png",
  },
  {
    id: "merch_scenttree_purple_elr_main_white",
    name: "Scent Tree - GTR Edition",
    price: 50,
    desc: "GTR edition scent tree",
    type: "tree",
    baseColor: "white",
    tags: ["main", "white"],
    img: "../src/img/merch/trees/merch_scenttree_purple_elr_main_white.png",
  },
  {
    id: "merch_scenttree_purple_elr_monogram_black",
    name: "Scent Tree - GTR Edition",
    price: 50,
    desc: "GTR edition scent tree",
    type: "tree",
    baseColor: "purple",
    tags: ["monogram", "black"],
    img: "../src/img/merch/trees/merch_scenttree_purple_elr_monogram_black.png",
  },
  {
    id: "merch_scenttree_purple_elr_monogram_white",
    name: "Scent Tree - GTR Edition",
    price: 50,
    desc: "GTR edition scent tree",
    type: "tree",
    baseColor: "purple",
    tags: ["monogram", "white"],
    img: "../src/img/merch/trees/merch_scenttree_purple_elr_monogram_white.png",
  },
  {
    id: "merch_scenttree_white_elr_gtr_black_orange",
    name: "Scent Tree - GTR Edition",
    price: 50,
    desc: "GTR edition scent tree",
    type: "tree",
    baseColor: "white",
    tags: ["gtr", "orange"],
    img: "../src/img/merch/trees/merch_scenttree_white_elr_gtr_black_orange.png",
  },
  {
    id: "merch_scenttree_white_elr_gtr_black_purple",
    name: "Scent Tree - GTR Edition",
    price: 50,
    desc: "GTR edition scent tree",
    type: "tree",
    baseColor: "white",
    tags: ["gtr", "purple"],
    img: "../src/img/merch/trees/merch_scenttree_white_elr_gtr_black_purple.png",
  },
  {
    id: "merch_scenttree_white_elr_gtr_black_red",
    name: "Scent Tree - GTR Edition",
    price: 50,
    desc: "GTR edition scent tree",
    type: "tree",
    baseColor: "white",
    tags: ["gtr", "red"],
    img: "../src/img/merch/trees/merch_scenttree_white_elr_gtr_black_red.png",
  },
  {
    id: "merch_scenttree_white_elr_gtr_black_stroke",
    name: "Scent Tree - GTR Edition",
    price: 50,
    desc: "GTR edition scent tree",
    type: "tree",
    baseColor: "white",
    tags: ["gtr", "black"],
    img: "../src/img/merch/trees/merch_scenttree_white_elr_gtr_black_stroke.png",
  },
  {
    id: "merch_scenttree_white_elr_main_black",
    name: "Scent Tree - GTR Edition",
    price: 50,
    desc: "GTR edition scent tree",
    type: "tree",
    baseColor: "white",
    tags: ["main", "black"],
    img: "../src/img/merch/trees/merch_scenttree_white_elr_main_black.png",
  },
  {
    id: "merch_scenttree_white_elr_main_orange",
    name: "Scent Tree - GTR Edition",
    price: 50,
    desc: "GTR edition scent tree",
    type: "tree",
    baseColor: "white",
    tags: ["main", "orange"],
    img: "../src/img/merch/trees/merch_scenttree_white_elr_main_orange.png",
  },
  {
    id: "merch_scenttree_white_elr_main_purple",
    name: "Scent Tree - GTR Edition",
    price: 50,
    desc: "GTR edition scent tree",
    type: "tree",
    baseColor: "white",
    tags: ["main", "purple"],
    img: "../src/img/merch/trees/merch_scenttree_white_elr_main_purple.png",
  },
  {
    id: "merch_scenttree_white_elr_monogram_black",
    name: "Scent Tree - GTR Edition",
    price: 50,
    desc: "GTR edition scent tree",
    type: "tree",
    baseColor: "white",
    tags: ["monogram", "black"],
    img: "../src/img/merch/trees/merch_scenttree_white_elr_monogram_black.png",
  },
  {
    id: "merch_scenttree_white_elr_monogram_gradient",
    name: "Scent Tree - GTR Edition",
    price: 50,
    desc: "GTR edition scent tree",
    type: "tree",
    baseColor: "white",
    tags: ["monogram", "color"],
    img: "../src/img/merch/trees/merch_scenttree_white_elr_monogram_gradient.png",
  },
  {
    id: "merch_scenttree_white_elr_monogram_purple",
    name: "Scent Tree - GTR Edition",
    price: 50,
    desc: "GTR edition scent tree",
    type: "tree",
    baseColor: "white",
    tags: ["monogram", "purple"],
    img: "../src/img/merch/trees/merch_scenttree_white_elr_monogram_purple.png",
  },
];
